title: fl9 blog
description: My notes
meta_description: "fl9 blog - my notes"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://blog.fl9.eu'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://blog.fl9.eu'
author:         'Michał Rudowicz'
authorTwitter:  'flegmatyk'

permalink:       /:year/:month/:day/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
